//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDelivery.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.RegionPostcodes = new HashSet<RegionPostcode>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<RegionPostcode> RegionPostcodes { get; set; }
    }
}
